/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;
import java.awt.event.KeyEvent;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
/**
/**
 *
 * @author ICTSTUDENT
 */
public class cashierform extends javax.swing.JFrame {
Connection conn=null;
PreparedStatement PST=null;
ResultSet RS=null;
Statement st;
    /**
     * Creates new form cashierform
     */
    public cashierform() {
       
        initComponents();
        setDefaultCloseOperation (cashierform.DISPOSE_ON_CLOSE);
        showdepth();
        showdepth1();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        csd = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        chomeno = new javax.swing.JTextField();
        cmobileno = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        caddress = new javax.swing.JTextArea();
        cname = new javax.swing.JTextField();
        nic = new javax.swing.JTextField();
        cpass = new javax.swing.JTextField();
        cid = new javax.swing.JTextField();
        addcashier = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        update = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        home = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 12, 6, 12, new java.awt.Color(0, 0, 0)));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "PASSWORD", "NAME", "NIC", "ADDRESS", "MOBILE NO", "HOME NO"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTable1MouseEntered(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(6).setResizable(false);
        }

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setText("ID");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setText("Password");

        csd.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        csd.setText("NIC");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("Name");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel4.setText("Address");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel5.setText("Mobile No");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel6.setText("Home No");

        chomeno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                chomenoKeyTyped(evt);
            }
        });

        cmobileno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cmobilenoKeyTyped(evt);
            }
        });

        caddress.setColumns(20);
        caddress.setRows(5);
        jScrollPane1.setViewportView(caddress);

        cname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cnameKeyTyped(evt);
            }
        });

        nic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nicKeyTyped(evt);
            }
        });

        cid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cidKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cidKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cidKeyTyped(evt);
            }
        });

        addcashier.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        addcashier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/images/add-24.png"))); // NOI18N
        addcashier.setText("ADD");
        addcashier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addcashierActionPerformed(evt);
            }
        });

        delete.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/images/delete-bin-24.png"))); // NOI18N
        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        update.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/images/update-left-rotation-24.png"))); // NOI18N
        update.setText("CHANGE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel1)
                            .addComponent(csd))
                        .addGap(58, 58, 58)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cid, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cpass, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nic, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cname, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmobileno, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chomeno, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(424, 424, 424)
                        .addComponent(addcashier)
                        .addGap(18, 18, 18)
                        .addComponent(update)
                        .addGap(18, 18, 18)
                        .addComponent(delete)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(csd))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmobileno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chomeno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addcashier)
                    .addComponent(update)
                    .addComponent(delete))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createMatteBorder(6, 12, 2, 12, new java.awt.Color(0, 0, 0)));

        home.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/images/home-24.png"))); // NOI18N
        home.setText("HOME");
        home.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel8.setText("CASHIER DETAILS");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(home)
                .addGap(241, 241, 241)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public ArrayList<cashierclass>cashierclasslist(String ValToSerach)
    {
    ArrayList<cashierclass> cashierclasslist=new ArrayList<>();
    try
    {
        conn=dbconnection.getConnection();
        PST=conn.prepareStatement("Select * from chasier where id=?;");
        PST=conn.prepareStatement("Select * from chasier");
        //PST=conn.prepareStatement("Select * from product where productcompanyname=?;");
        PST.setString(1, cid.getText());
        //PST.setString(1, companyproductcbox.getSelectedItem().toString());
        RS=PST.executeQuery();
        cashierclass cashierclass;
        while(RS.next())
        {
        
            cashierclass = new cashierclass(RS.getString("id"),RS.getString("password"),RS.getString("name"),RS.getString("nic"),RS.getString("address"),RS.getString("mobilenumber"),RS.getString("homenumber"));
            cashierclasslist.add(cashierclass);
        }
    
    }
    catch(SQLException e)
    {
        //JOptionPane.showMessageDialog(null, e);
    }
    return cashierclasslist;
    }
    
   // ...............................................................................................................Search Table........................
    
    public ArrayList<cashierclass>cashierclasslist()
    {
    ArrayList<cashierclass> cashierclasslist=new ArrayList<>();
    try
    {
        conn=dbconnection.getConnection();
        
        PST=conn.prepareStatement("Select * from chasier;");
        st=conn.createStatement();
        RS=st.executeQuery("Select * from chasier;");
        
        cashierclass cashierclass;
        while(RS.next())
        {
        
            cashierclass = new cashierclass(RS.getString("id"),RS.getString("password"),RS.getString("name"),RS.getString("nic"),RS.getString("address"),RS.getString("mobilenumber"),RS.getString("homenumber"));
            cashierclasslist.add(cashierclass);
        }
    
    }
    catch(SQLException e)
    {
        //JOptionPane.showMessageDialog(null, e);
    }
    return cashierclasslist;
    }
    private void addcashierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addcashierActionPerformed
        // TODO add your handling code here:
        
        try{
            String query="INSERT INTO chasier(id,password,name,nic,address,mobilenumber,homenumber)values(?,?,?,?,?,?,?)";
            conn=dbconnection.getConnection();
            PST=conn.prepareStatement(query);

            PST.setString(1,cid.getText());
            PST.setString(2,cpass.getText());
            PST.setString(3,cname.getText());
            PST.setString(4,nic.getText());
            PST.setString(5,caddress.getText());
            PST.setString(6,cmobileno.getText());
            PST.setString(7,chomeno.getText());

            PST.executeUpdate();
            System.out.println("gotline");
            JOptionPane.showMessageDialog(null, "Insert Succesfully");

        }
        catch(SQLException ex)
        {
            System.out.println("gotline");
            JOptionPane.showMessageDialog(null, "Duplicate Update");

            System.err.println(ex);
        }
        DefaultTableModel df=(DefaultTableModel)jTable1.getModel();
        while(df.getRowCount()>0)
        {
            df.removeRow(0);
        }
        showdepth1();
        cid.setText("");
        cpass.setText("");
        nic.setText("");
        cname.setText("");
        caddress.setText("");
        cmobileno.setText("");
        chomeno.setText("");
        cid.setText("");
    }//GEN-LAST:event_addcashierActionPerformed

    private void cidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cidKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cidKeyPressed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        try{
            String query="UPDATE  chasier set password=?,name=?,nic=?,address=?,mobilenumber=?,homenumber=? where id=?";
            conn = dbconnection.getConnection();
            PST = conn.prepareStatement(query);

            //PST.setString(1, cid.getText());
            PST.setString(1, cpass.getText());
            PST.setString(2, cname.getText());
            PST.setString(3,nic.getText());
            
            PST.setString(4, caddress.getText());
            PST.setString(5, cmobileno.getText());
            PST.setString(6, chomeno.getText());
            PST.setString(7, cid.getText());
            
            PST.executeUpdate();
            System.out.println("gotline");
            JOptionPane.showMessageDialog(null, "update sucessfully!!");

        } catch (SQLException ex) {
            System.out.println(ex);
            JOptionPane.showMessageDialog(null, "Dublicate update !!");

        }
        DefaultTableModel df=(DefaultTableModel)jTable1.getModel();
        while(df.getRowCount()>0)
        {
            df.removeRow(0);
        }
        showdepth1();
        //.............................................Clear Codding.....................................
        cid.setText("");
        cpass.setText("");
        nic.setText("");
        cname.setText("");
        caddress.setText("");
        cmobileno.setText("");
        chomeno.setText("");
        cid.setText("");
    }//GEN-LAST:event_updateActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int i=jTable1.getSelectedRow();
        TableModel model=jTable1.getModel();
        cid.setText(model.getValueAt(i,0).toString());
        cpass.setText(model.getValueAt(i,1).toString());
        cname.setText(model.getValueAt(i,2).toString());
        nic.setText(model.getValueAt(i,3).toString());
        caddress.setText(model.getValueAt(i,4).toString());
        cmobileno.setText(model.getValueAt(i,5).toString());
        chomeno.setText(model.getValueAt(i,6).toString());
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void cidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cidKeyReleased
        // TODO add your handling code here:
        showdepth();
    }//GEN-LAST:event_cidKeyReleased

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
         try{
            conn=dbconnection.getConnection();
            PST=conn.prepareStatement("DELETE FROM chasier Where id=?");
            PST.setString(1,cid.getText());
            PST.executeUpdate();

            JOptionPane.showMessageDialog(null, "Delete sucessfully!!");

        } catch (SQLException ex) {
            Logger.getLogger(productform.class.getName()).log(Level.SEVERE, null, ex);

        }
        DefaultTableModel df=(DefaultTableModel)jTable1.getModel();
        while(df.getRowCount()>0)
        {
            df.removeRow(0);
        }
        showdepth1();
        /*try{
            conn = buymoredbClass.getConnection();
            PST = conn.prepareStatement("SELECT nic from newuser");
            RS=PST.executeQuery();
            while(RS.next())
            {
                String did=RS.getString("nic");
                pcname.addItem(did);
            }
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex);*/

            cid.setText("");
            cpass.setText("");
            cname.setText("");
            nic.setText("");
            caddress.setText("");
            cmobileno.setText("");
            chomeno.setText("");
            
    }//GEN-LAST:event_deleteActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here:
        new salespage().setVisible(true);
    }//GEN-LAST:event_homeActionPerformed

    private void cnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cnameKeyTyped
        // TODO add your handling code here:
         char c=evt.getKeyChar(); //get input from text field character by character
       if (!((Character.isAlphabetic(c)) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE ||(c == KeyEvent.VK_PERIOD)))) 
      {
       getToolkit().beep();
       evt.consume();
      }
         
    }//GEN-LAST:event_cnameKeyTyped

    private void cmobilenoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmobilenoKeyTyped
        // TODO add your handling code here:
         char c=evt.getKeyChar(); //get input from text field character by character
       if (!((c >= '0') && ('9' >= c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) 
      {
       getToolkit().beep();
       evt.consume();
      }
         if(cmobileno.getText().length()>=10)
        {
            evt.consume();
        }
    }//GEN-LAST:event_cmobilenoKeyTyped

    private void chomenoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_chomenoKeyTyped
        // TODO add your handling code here:
         char c=evt.getKeyChar(); //get input from text field character by character
       if (!((c >= '0') && ('9' >= c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE ))) 
      {
       getToolkit().beep();
       evt.consume();
      }
       if(chomeno.getText().length()>=10)
        {
            evt.consume();
        }
    }//GEN-LAST:event_chomenoKeyTyped

    private void jTable1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseEntered

    private void nicKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nicKeyTyped
        // TODO add your handling code here:
        if(nic.getText().length()>=11)
        {
            evt.consume();
        }
    }//GEN-LAST:event_nicKeyTyped

    private void cidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cidKeyTyped
        // TODO add your handling code here:
         if(nic.getText().length()>=10)
        {
            evt.consume();
        }
    }//GEN-LAST:event_cidKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cashierform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cashierform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cashierform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cashierform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new cashierform().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addcashier;
    private javax.swing.JTextArea caddress;
    private javax.swing.JTextField chomeno;
    private javax.swing.JTextField cid;
    private javax.swing.JTextField cmobileno;
    private javax.swing.JTextField cname;
    private javax.swing.JTextField cpass;
    private javax.swing.JLabel csd;
    private javax.swing.JButton delete;
    private javax.swing.JButton home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nic;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables

    private void showdepth() {
        ArrayList<cashierclass> list=cashierclasslist(cid.getText());
        DefaultTableModel model=new DefaultTableModel();
        model.setColumnIdentifiers(new Object[]{"id","password","name","nic","address","mobilenumber","homenumber"});
        Object [] row=new Object[7];
        
        for(int i=0;i<list.size();i++)
        {
            row[0]=list.get(i).getid();
            row[1]=list.get(i).getpassword();
            row[2]=list.get(i).getname();
            row[3]=list.get(i).getnic();
            row[4]=list.get(i).getaddress();
            row[5]=list.get(i).getmobilenumber();
            row[6]=list.get(i).gethomenumber();
            
            
            model.addRow(row);
        }
        jTable1.setModel(model);
        
    }
       //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.

    private void showdepth1() {
        ArrayList<cashierclass> list=cashierclasslist();
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        model.setColumnIdentifiers(new Object[]{"id","password","name","nic","address","mobilenumber","homenumber"});
        Object [] row=new Object[7];
        
        for(int i=0;i<list.size();i++)
        {
            row[0]=list.get(i).getid();
            row[1]=list.get(i).getpassword();
            row[2]=list.get(i).getname();
            row[3]=list.get(i).getnic();
            row[4]=list.get(i).getaddress();
            row[5]=list.get(i).getmobilenumber();
            row[6]=list.get(i).gethomenumber();
            
            
            model.addRow(row);
        }
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    }

