/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
/**
 *
 * @author ICTSTUDENT
 */
public class productform extends javax.swing.JFrame {
Connection conn=null;
PreparedStatement PST=null;
ResultSet RS=null;
Statement st;
    /**
     * Creates new form productform
     */
    public productform() {
        
        initComponents();
        setDefaultCloseOperation (productform.DISPOSE_ON_CLOSE);
        comload();
        showdepth();
        showdepth1();

        new Thread(){
         
            
            @Override
            public void run(){
                while(true){
                    Date dNow = new Date( );{
                    
                    SimpleDateFormat ft = new SimpleDateFormat ("yyyy-MM-dd");
                    String time = ""+ft.format(dNow);
                    SimpleDateFormat bn = new SimpleDateFormat ("E hh:mm:ss a");
                    String time1 = ""+bn.format(dNow);
                    
                    jLabel7.setText(time);
                    jLabel9.setText(time1);
                    
                }
                
            }
            }
        } .start();
         
         
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        home = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        update = new javax.swing.JButton();
        pid = new javax.swing.JTextField();
        delete = new javax.swing.JButton();
        pname = new javax.swing.JTextField();
        pcname = new javax.swing.JComboBox<>();
        pp = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        snp = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pq = new javax.swing.JTextField();
        newproductadd = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(6, 12, 2, 12, new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("PRODUCT DETAILS");

        home.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/images/back-48.png"))); // NOI18N
        home.setText("BACK");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });

        jLabel9.setText("jLabel9");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(home)
                .addGap(53, 53, 53)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 12, 6, 12, new java.awt.Color(0, 0, 0)));

        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanel2.setRequestFocusEnabled(false);
        jPanel2.setVerifyInputWhenFocusTarget(false);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("PRODUCT QTY");

        update.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/images/update-left-rotation-24.png"))); // NOI18N
        update.setText("CHANGE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        pid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pidKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pidKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pidKeyTyped(evt);
            }
        });

        delete.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/images/delete-bin-24.png"))); // NOI18N
        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        pname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pnameKeyTyped(evt);
            }
        });

        pp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ppKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ppKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("PRODUCT ID");

        snp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                snpKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("PRODUCT NAME");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("PURCHESING PRICE");

        pq.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pqKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pqKeyTyped(evt);
            }
        });

        newproductadd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        newproductadd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/images/add-24.png"))); // NOI18N
        newproductadd.setText("SAVE");
        newproductadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newproductaddActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("SELLING NORMAL PRICE");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("PRODUCT COMPANY NAME");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PRODUCT ID", "PRODUCT NAME", "COMPANY", "PURCHESE PRICE", "QTY", "SELLING PRICE"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/images/company-24.png"))); // NOI18N
        jButton1.setText("ADD NEW COMPANY");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel8)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(snp, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pp)
                    .addComponent(pcname, 0, 194, Short.MAX_VALUE)
                    .addComponent(pname)
                    .addComponent(pid, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pq))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(newproductadd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(update)
                        .addGap(26, 26, 26)
                        .addComponent(delete)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 743, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pcname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(snp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newproductadd)
                    .addComponent(update)
                    .addComponent(delete)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
                                                   
    public ArrayList<Project>Projectlist(String ValToSerach)
    {
    ArrayList<Project> Projectlist=new ArrayList<>();
    try
    {
        conn=dbconnection.getConnection();
        PST=conn.prepareStatement("Select * from product where productid=?");
        //PST=conn.prepareStatement("Select * from product where productcompanyname=?;");
        PST.setString(1, pid.getText());
        //PST.setString(1, companyproductcbox.getSelectedItem().toString());
        RS=PST.executeQuery();
        Project Project;
        while(RS.next())
        {
        
            Project=new Project(RS.getString("productid"),RS.getString("productname"),RS.getString("productcompanyname"),RS.getString("productunitprice"),RS.getString("productqty"),RS.getString("productnormalprice"));
            Projectlist.add(Project);
        }
    
    }
    catch(SQLException e)
    {
        //JOptionPane.showMessageDialog(null, e);
    }
    return Projectlist;
    }
    //.......................................all Product search.............................................
    
    public ArrayList<Project>Projectlist()
    {
    ArrayList<Project> Projectlist=new ArrayList<>();
    try
    {
        conn=dbconnection.getConnection();
        PST=conn.prepareStatement("Select * from product ;");
        st=conn.createStatement();
        RS=st.executeQuery("Select * from product ");
        Project Project;
        while(RS.next())
        {
        
            Project=new Project(RS.getString("productid"),RS.getString("productname"),RS.getString("productcompanyname"),RS.getString("productunitprice"),RS.getString("productqty"),RS.getString("productnormalprice"));
            Projectlist.add(Project);
        }
    
    }
    catch(SQLException e)
    {
        //JOptionPane.showMessageDialog(null, e);
    }
    return Projectlist;
    }
    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        try{
            String query="UPDATE  product set productid=?,productname=?,productcompanyname=?,productunitprice=?,productnormalprice=?,productqty=? where productid=?";
            conn = dbconnection.getConnection();
            PST = conn.prepareStatement(query);

            PST.setString(1, pid.getText());
            PST.setString(2, pname.getText());

            String productcompanyname=null;
            productcompanyname=pcname.getSelectedItem().toString();
            PST.setString(3,productcompanyname);
            PST.setString(4, pp.getText());
            PST.setString(5, snp.getText());
            
            PST.setString(6, pq.getText());
            PST.setString(7, pid.getText());
            
            PST.executeUpdate();
            System.out.println("gotline");
            JOptionPane.showMessageDialog(null, "update sucessfully!!");

        } catch (SQLException ex) {
            System.out.println(ex);
            JOptionPane.showMessageDialog(null, "Dublicate update !!");

        }
        DefaultTableModel dt=(DefaultTableModel)jTable1.getModel();
        while(dt.getRowCount()>0)
        {
            dt.removeRow(0);
            
        }
        showdepth1();
        pid.setText("");
        pname.setText("");
        pcname.setSelectedItem("");
        pp.setText("");
        pq.setText("");
        snp.setText("");
        
    }//GEN-LAST:event_updateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:

        try{
            conn=dbconnection.getConnection();
            PST=conn.prepareStatement("DELETE FROM product Where productid=?");
            PST.setString(1,pid.getText());
            PST.executeUpdate();

            JOptionPane.showMessageDialog(null, "Delete sucessfully!!");

        } catch (SQLException ex) {
            Logger.getLogger(productform.class.getName()).log(Level.SEVERE, null, ex);

        }
        DefaultTableModel dt=(DefaultTableModel)jTable1.getModel();
        while(dt.getRowCount()>0)
        {
            dt.removeRow(0);
            
        }
        showdepth1();
            pid.setText("");
            pname.setText("");
            pcname.setSelectedItem("");
            pp.setText("");
            pq.setText("");
           
            snp.setText("");
            DefaultTableModel df=(DefaultTableModel)jTable1.getModel();
        while(df.getRowCount()>0)
        {
            df.removeRow(0);
        }
            
    }//GEN-LAST:event_deleteActionPerformed

    private void newproductaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newproductaddActionPerformed
        // TODO add your handling code here:
        
        try{
            String query="INSERT INTO product(productid,productname,productcompanyname,productunitprice,productnormalprice,productqty)values(?,?,?,?,?,?)";
            conn=dbconnection.getConnection();
            PST=conn.prepareStatement(query);

            PST.setString(1,pid.getText());
            PST.setString(2,pname.getText());
            PST.setString(3,pcname.getSelectedItem().toString());
            PST.setString(4,pp.getText());
            PST.setString(5,snp.getText());
            
            PST.setString(6,pq.getText());

            PST.executeUpdate();
            System.out.println("gotline");
            JOptionPane.showMessageDialog(null, "Insert Succesfully");

        }
        catch(SQLException ex)
        {
//            System.out.println("gotline");
            JOptionPane.showMessageDialog(null, "Duplicate Update");

            System.err.println(ex);
        }
        DefaultTableModel df=(DefaultTableModel)jTable1.getModel();
        while(df.getRowCount()>0)
        {
            df.removeRow(0);
        }
        showdepth1();
         pid.setText("");
         pname.setText("");
         pcname.setSelectedItem("");
         pp.setText("");
         pq.setText("");
           
         snp.setText("");
    }//GEN-LAST:event_newproductaddActionPerformed

    private void pidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pidKeyPressed
        // TODO add your handling code here:
        //showdepth();
    }//GEN-LAST:event_pidKeyPressed

    private void pidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pidKeyReleased
        // TODO add your handling code here:
        showdepth();
    }//GEN-LAST:event_pidKeyReleased

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int i=jTable1.getSelectedRow();
        TableModel model=jTable1.getModel();
        pid.setText(model.getValueAt(i,0).toString());
        pname.setText(model.getValueAt(i,1).toString());
        pcname.setSelectedItem(model.getValueAt(i,2).toString());
        pp.setText(model.getValueAt(i,3).toString());
        snp.setText(model.getValueAt(i,4).toString());
        pq.setText(model.getValueAt(i,5).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_homeActionPerformed

    private void pidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pidKeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar(); //get input from text field character by character
        if (!((c >= '0') && ('9' >= c)))
        {
            getToolkit().beep();
            evt.consume();
        }
        if(pid.getText().length()>=4)
        {
            evt.consume();
        }
    }//GEN-LAST:event_pidKeyTyped

    private void pnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pnameKeyTyped
        // TODO add your handling code here:
        if(pname.getText().length()>=25)
        {
            evt.consume();
        }
    }//GEN-LAST:event_pnameKeyTyped

    private void pqKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pqKeyTyped
      char c=evt.getKeyChar(); //get input from text field character by character
       if (!((c >= '0') && ('9' >= c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) 
      {
       getToolkit().beep();
       evt.consume();  
      }        // TODO add your handling code here:
        if(pq.getText().length()>=5)
        {
            evt.consume();
        }
    }//GEN-LAST:event_pqKeyTyped

    private void ppKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ppKeyTyped
        // TODO add your handling code here:
         
//        System.out.println(formatted);
        char c=evt.getKeyChar(); //get input from text field character by character
       if (!((c >= '0') && ('9' >= c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE ||(c == KeyEvent.VK_PERIOD)))) 
           
      {
       
       getToolkit().beep();
       evt.consume();
      }
     if(pp.getText().length()>=8)
        {
            evt.consume();
        }
        
    }//GEN-LAST:event_ppKeyTyped

    private void snpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_snpKeyTyped
        // TODO add your handling code here:
         char c=evt.getKeyChar(); //get input from text field character by character
       if (!((c >= '0') && ('9' >= c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE ||(c == KeyEvent.VK_PERIOD)))) 
      {
       getToolkit().beep();
       evt.consume();
      }
       if(snp.getText().length()>=8)
        {
            evt.consume();
        }
    }//GEN-LAST:event_snpKeyTyped

    private void ppKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ppKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_ppKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new companydetails().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void pqKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pqKeyReleased
        // TODO add your handling code here:
      
    }//GEN-LAST:event_pqKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(productform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(productform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(productform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(productform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new productform().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton delete;
    private javax.swing.JButton home;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton newproductadd;
    private javax.swing.JComboBox<String> pcname;
    private javax.swing.JTextField pid;
    private javax.swing.JTextField pname;
    private javax.swing.JTextField pp;
    private javax.swing.JTextField pq;
    private javax.swing.JTextField snp;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables

    private void comload() {
        try{
            conn=dbconnection.getConnection();
            PST=conn.prepareStatement("SELECT companyname FROM company");
            RS=PST.executeQuery();
            while(RS.next())
            {
                String did=RS.getString("companyname");
                pcname.addItem(did);
            }
            } 
        catch (SQLException ex) 
        {
            JOptionPane.showMessageDialog(null,ex);
        }
        
    }

    private void showdepth() {
        ArrayList<Project> list=Projectlist(pid.getText());
        DefaultTableModel model=new DefaultTableModel();
        model.setColumnIdentifiers(new Object[]{"productid","productname","productcompanyname","BuyPrice","SellPrice","productqty"});
        Object [] row=new Object[6];
        
        for(int i=0;i<list.size();i++)
        {
            row[0]=list.get(i).getproductid();
            row[1]=list.get(i).getproductname();
            row[2]=list.get(i).getproductcompanyname();
            row[3]=list.get(i).getproductunitprice();
            row[4]=list.get(i).getproductnormalprice();
            row[5]=list.get(i).getproductqty();
            
            model.addRow(row);
        }
        jTable1.setModel(model);
        
    }

    private void showdepth1() {
        ArrayList<Project> list=Projectlist();
        DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
        model.setColumnIdentifiers(new Object[]{"productid","productname","productcompanyname","BuyPrice","SellPrice","productqty"});
        Object [] row=new Object[6];
        
        for(int i=0;i<list.size();i++)
        {
            row[0]=list.get(i).getproductid();
            row[1]=list.get(i).getproductname();
            row[2]=list.get(i).getproductcompanyname();
            row[3]=list.get(i).getproductunitprice();
            row[4]=list.get(i).getproductnormalprice();
            row[5]=list.get(i).getproductqty();
            
            
            model.addRow(row);
        }
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
